/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IcmsDiagnosticoRouteImport } from './routes/icms-diagnostico'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as DigitalWorkerRouteImport } from './routes/digital-worker'
import { Route as AutonomousFinanceRouteImport } from './routes/autonomous-finance'
import { Route as IndexRouteImport } from './routes/index'

const IcmsDiagnosticoRoute = IcmsDiagnosticoRouteImport.update({
  id: '/icms-diagnostico',
  path: '/icms-diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalWorkerRoute = DigitalWorkerRouteImport.update({
  id: '/digital-worker',
  path: '/digital-worker',
  getParentRoute: () => rootRouteImport,
} as any)
const AutonomousFinanceRoute = AutonomousFinanceRouteImport.update({
  id: '/autonomous-finance',
  path: '/autonomous-finance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/autonomous-finance': typeof AutonomousFinanceRoute
  '/digital-worker': typeof DigitalWorkerRoute
  '/financeiro': typeof FinanceiroRoute
  '/icms-diagnostico': typeof IcmsDiagnosticoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/autonomous-finance': typeof AutonomousFinanceRoute
  '/digital-worker': typeof DigitalWorkerRoute
  '/financeiro': typeof FinanceiroRoute
  '/icms-diagnostico': typeof IcmsDiagnosticoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/autonomous-finance': typeof AutonomousFinanceRoute
  '/digital-worker': typeof DigitalWorkerRoute
  '/financeiro': typeof FinanceiroRoute
  '/icms-diagnostico': typeof IcmsDiagnosticoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/autonomous-finance'
    | '/digital-worker'
    | '/financeiro'
    | '/icms-diagnostico'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/autonomous-finance'
    | '/digital-worker'
    | '/financeiro'
    | '/icms-diagnostico'
  id:
    | '__root__'
    | '/'
    | '/autonomous-finance'
    | '/digital-worker'
    | '/financeiro'
    | '/icms-diagnostico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutonomousFinanceRoute: typeof AutonomousFinanceRoute
  DigitalWorkerRoute: typeof DigitalWorkerRoute
  FinanceiroRoute: typeof FinanceiroRoute
  IcmsDiagnosticoRoute: typeof IcmsDiagnosticoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/icms-diagnostico': {
      id: '/icms-diagnostico'
      path: '/icms-diagnostico'
      fullPath: '/icms-diagnostico'
      preLoaderRoute: typeof IcmsDiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-worker': {
      id: '/digital-worker'
      path: '/digital-worker'
      fullPath: '/digital-worker'
      preLoaderRoute: typeof DigitalWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autonomous-finance': {
      id: '/autonomous-finance'
      path: '/autonomous-finance'
      fullPath: '/autonomous-finance'
      preLoaderRoute: typeof AutonomousFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutonomousFinanceRoute: AutonomousFinanceRoute,
  DigitalWorkerRoute: DigitalWorkerRoute,
  FinanceiroRoute: FinanceiroRoute,
  IcmsDiagnosticoRoute: IcmsDiagnosticoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
