/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IcmsTransicaoRouteImport } from './routes/icms-transicao'
import { Route as IcmsDiagnosticoRouteImport } from './routes/icms-diagnostico'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as FinanceTransicaoRouteImport } from './routes/finance-transicao'
import { Route as DigitalWorkerRouteImport } from './routes/digital-worker'
import { Route as ComplianceTransicaoRouteImport } from './routes/compliance-transicao'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as AutonomousFinanceRouteImport } from './routes/autonomous-finance'
import { Route as ApuracaoTransicaoRouteImport } from './routes/apuracao-transicao'
import { Route as ApuracaoSimulacaoRouteImport } from './routes/apuracao-simulacao'
import { Route as IndexRouteImport } from './routes/index'

const IcmsTransicaoRoute = IcmsTransicaoRouteImport.update({
  id: '/icms-transicao',
  path: '/icms-transicao',
  getParentRoute: () => rootRouteImport,
} as any)
const IcmsDiagnosticoRoute = IcmsDiagnosticoRouteImport.update({
  id: '/icms-diagnostico',
  path: '/icms-diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceTransicaoRoute = FinanceTransicaoRouteImport.update({
  id: '/finance-transicao',
  path: '/finance-transicao',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalWorkerRoute = DigitalWorkerRouteImport.update({
  id: '/digital-worker',
  path: '/digital-worker',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceTransicaoRoute = ComplianceTransicaoRouteImport.update({
  id: '/compliance-transicao',
  path: '/compliance-transicao',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AutonomousFinanceRoute = AutonomousFinanceRouteImport.update({
  id: '/autonomous-finance',
  path: '/autonomous-finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApuracaoTransicaoRoute = ApuracaoTransicaoRouteImport.update({
  id: '/apuracao-transicao',
  path: '/apuracao-transicao',
  getParentRoute: () => rootRouteImport,
} as any)
const ApuracaoSimulacaoRoute = ApuracaoSimulacaoRouteImport.update({
  id: '/apuracao-simulacao',
  path: '/apuracao-simulacao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apuracao-simulacao': typeof ApuracaoSimulacaoRoute
  '/apuracao-transicao': typeof ApuracaoTransicaoRoute
  '/autonomous-finance': typeof AutonomousFinanceRoute
  '/compliance': typeof ComplianceRoute
  '/compliance-transicao': typeof ComplianceTransicaoRoute
  '/digital-worker': typeof DigitalWorkerRoute
  '/finance-transicao': typeof FinanceTransicaoRoute
  '/financeiro': typeof FinanceiroRoute
  '/icms-diagnostico': typeof IcmsDiagnosticoRoute
  '/icms-transicao': typeof IcmsTransicaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apuracao-simulacao': typeof ApuracaoSimulacaoRoute
  '/apuracao-transicao': typeof ApuracaoTransicaoRoute
  '/autonomous-finance': typeof AutonomousFinanceRoute
  '/compliance': typeof ComplianceRoute
  '/compliance-transicao': typeof ComplianceTransicaoRoute
  '/digital-worker': typeof DigitalWorkerRoute
  '/finance-transicao': typeof FinanceTransicaoRoute
  '/financeiro': typeof FinanceiroRoute
  '/icms-diagnostico': typeof IcmsDiagnosticoRoute
  '/icms-transicao': typeof IcmsTransicaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apuracao-simulacao': typeof ApuracaoSimulacaoRoute
  '/apuracao-transicao': typeof ApuracaoTransicaoRoute
  '/autonomous-finance': typeof AutonomousFinanceRoute
  '/compliance': typeof ComplianceRoute
  '/compliance-transicao': typeof ComplianceTransicaoRoute
  '/digital-worker': typeof DigitalWorkerRoute
  '/finance-transicao': typeof FinanceTransicaoRoute
  '/financeiro': typeof FinanceiroRoute
  '/icms-diagnostico': typeof IcmsDiagnosticoRoute
  '/icms-transicao': typeof IcmsTransicaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apuracao-simulacao'
    | '/apuracao-transicao'
    | '/autonomous-finance'
    | '/compliance'
    | '/compliance-transicao'
    | '/digital-worker'
    | '/finance-transicao'
    | '/financeiro'
    | '/icms-diagnostico'
    | '/icms-transicao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apuracao-simulacao'
    | '/apuracao-transicao'
    | '/autonomous-finance'
    | '/compliance'
    | '/compliance-transicao'
    | '/digital-worker'
    | '/finance-transicao'
    | '/financeiro'
    | '/icms-diagnostico'
    | '/icms-transicao'
  id:
    | '__root__'
    | '/'
    | '/apuracao-simulacao'
    | '/apuracao-transicao'
    | '/autonomous-finance'
    | '/compliance'
    | '/compliance-transicao'
    | '/digital-worker'
    | '/finance-transicao'
    | '/financeiro'
    | '/icms-diagnostico'
    | '/icms-transicao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApuracaoSimulacaoRoute: typeof ApuracaoSimulacaoRoute
  ApuracaoTransicaoRoute: typeof ApuracaoTransicaoRoute
  AutonomousFinanceRoute: typeof AutonomousFinanceRoute
  ComplianceRoute: typeof ComplianceRoute
  ComplianceTransicaoRoute: typeof ComplianceTransicaoRoute
  DigitalWorkerRoute: typeof DigitalWorkerRoute
  FinanceTransicaoRoute: typeof FinanceTransicaoRoute
  FinanceiroRoute: typeof FinanceiroRoute
  IcmsDiagnosticoRoute: typeof IcmsDiagnosticoRoute
  IcmsTransicaoRoute: typeof IcmsTransicaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/icms-transicao': {
      id: '/icms-transicao'
      path: '/icms-transicao'
      fullPath: '/icms-transicao'
      preLoaderRoute: typeof IcmsTransicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icms-diagnostico': {
      id: '/icms-diagnostico'
      path: '/icms-diagnostico'
      fullPath: '/icms-diagnostico'
      preLoaderRoute: typeof IcmsDiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-transicao': {
      id: '/finance-transicao'
      path: '/finance-transicao'
      fullPath: '/finance-transicao'
      preLoaderRoute: typeof FinanceTransicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-worker': {
      id: '/digital-worker'
      path: '/digital-worker'
      fullPath: '/digital-worker'
      preLoaderRoute: typeof DigitalWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance-transicao': {
      id: '/compliance-transicao'
      path: '/compliance-transicao'
      fullPath: '/compliance-transicao'
      preLoaderRoute: typeof ComplianceTransicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autonomous-finance': {
      id: '/autonomous-finance'
      path: '/autonomous-finance'
      fullPath: '/autonomous-finance'
      preLoaderRoute: typeof AutonomousFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apuracao-transicao': {
      id: '/apuracao-transicao'
      path: '/apuracao-transicao'
      fullPath: '/apuracao-transicao'
      preLoaderRoute: typeof ApuracaoTransicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apuracao-simulacao': {
      id: '/apuracao-simulacao'
      path: '/apuracao-simulacao'
      fullPath: '/apuracao-simulacao'
      preLoaderRoute: typeof ApuracaoSimulacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApuracaoSimulacaoRoute: ApuracaoSimulacaoRoute,
  ApuracaoTransicaoRoute: ApuracaoTransicaoRoute,
  AutonomousFinanceRoute: AutonomousFinanceRoute,
  ComplianceRoute: ComplianceRoute,
  ComplianceTransicaoRoute: ComplianceTransicaoRoute,
  DigitalWorkerRoute: DigitalWorkerRoute,
  FinanceTransicaoRoute: FinanceTransicaoRoute,
  FinanceiroRoute: FinanceiroRoute,
  IcmsDiagnosticoRoute: IcmsDiagnosticoRoute,
  IcmsTransicaoRoute: IcmsTransicaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
